# Use this configuration to deploy the full LangSmith observability stack with filesystem storage.
# You can disable parts as you see fit, such as exporters, or logs/metrics/traces.
# NOTE: This should not be used as a production observability system, but rather to gain quick insights into your LangSmith deployment.

langsmithNamespace: "langsmith" # Change this value to match your LangSmith namespace.
langSmithReleaseName: "langsmith" # Change this value to match your LangSmith release name.

# ======================== Metrics Exporters ========================
kube-state-metrics:
  enabled: true
  # Change this value to match your LangSmith namespace.
  namespaces: "langsmith"

postgres-exporter:
  enabled: true
  config:
    # Change these values to match your Postgres instance.
    datasource:
      host: langsmith-postgres.langsmith.svc.cluster.local
      user: postgres
      password: postgres
      database: postgres
      port: "5432"

nginx-exporter:
  enabled: true
  # Change this value to match your LangSmith frontend service.
  nginxServer: "http://langsmith-frontend.langsmith.svc.cluster.local:80/nginx_status"

redis-exporter:
  enabled: true
  # Change this value to match your Redis instance.
  redisAddress: langsmith-redis.langsmith.svc.cluster.local:6379

# ======================== OTEL Collector ========================
otelCollector:
  logs:
    enabled: true
  metrics:
    enabled: true
  traces:
    enabled: true
    
# ======================== LGTM Stack ========================
# Telemetry visualization tool
grafana:
  enabled: true

# Logging storage + retrieval
loki:
  enabled: true
        
# Metrics storage + retrieval
mimir:
  enabled: true

# Traces storage + retrieval
tempo:
  enabled: true