{{- if and .Values.ingestQueue.enabled .Values.ingestQueue.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.ingestQueue.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.ingestQueue.pdb.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.ingestQueue.pdb.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.ingestQueue.name }}
  {{- if .Values.ingestQueue.pdb.minAvailable }}
  minAvailable: {{ .Values.ingestQueue.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.ingestQueue.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.ingestQueue.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
