apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-upstream
  labels:
    app: echo-upstream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-upstream
  template:
    metadata:
      labels:
        app: echo-upstream
    spec:
      containers:
        - name: echo
          image: mendhak/http-https-echo:35
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "10001"
---
apiVersion: v1
kind: Service
metadata:
  name: echo-upstream
  labels:
    app: echo-upstream
spec:
  selector:
    app: echo-upstream
  ports:
    - port: 10001
      targetPort: 10001
      protocol: TCP
