apiVersion: v2
name: langsmith
maintainers:
  - name: Ankush
    email: ankush@langchain.dev
description: Helm chart to deploy the langsmith application and all services it depends on.
type: application
version: 0.6.15
appVersion: "0.6.28"
