{{- if not .Values.config.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.secretsName" . }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  openai_api_key: {{ .Values.config.openaiApiKey | b64enc | quote }}
  oauth_client_id: {{ .Values.config.oauth.oauthClientId | b64enc | quote }}
  oauth_issuer_url: {{ .Values.config.oauth.oauthIssuerUrl | b64enc | quote }}
  langsmith_license_key: {{ .Values.config.langsmithLicenseKey | b64enc | quote }}
  api_key_salt: {{ .Values.config.apiKeySalt | default .Values.config.langsmithLicenseKey | b64enc | quote }}
  jwt_secret: {{ .Values.config.basicAuth.jwtSecret | b64enc | quote }}
  initial_org_admin_password: {{ .Values.config.basicAuth.initialOrgAdminPassword | b64enc | quote }}
  blob_storage_access_key: {{ .Values.config.blobStorage.accessKey | b64enc | quote }}
  blob_storage_access_key_secret: {{ .Values.config.blobStorage.accessKeySecret | b64enc | quote }}
{{- end }}
