{{- if .Values.backend.feedbackConfigMigration.enabled }}
{{- $envVars := concat .Values.commonEnv (include "langsmith.commonEnv" . | fromYamlArray) .Values.backend.feedbackConfigMigration.extraEnv -}}
{{- include "langsmith.detectDuplicates" $envVars -}}
{{- $volumes := concat .Values.commonVolumes .Values.backend.feedbackConfigMigration.volumes (include "langsmith.tlsVolumes" . | fromYamlArray) -}}
{{- $volumeMounts := concat .Values.commonVolumeMounts .Values.backend.feedbackConfigMigration.volumeMounts (include "langsmith.tlsVolumeMounts" . | fromYamlArray) -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.backend.name }}-config-migrations{{ ternary (printf "-%s" (randAlphaNum 5 | lower)) ""  .Values.backend.feedbackConfigMigration.randomizeName }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.backend.feedbackConfigMigration.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "1"
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.backend.feedbackConfigMigration.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: {{ .Values.backend.feedbackConfigMigration.ttlSecondsAfterFinished }}
  template:
    metadata:
      {{- with .Values.backend.feedbackConfigMigration.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.backend.feedbackConfigMigration.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.backend.name }}
    spec:
      restartPolicy: Never
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "langsmith.podSecurityContext" (dict "Values" .Values "componentSecurityContext" .Values.backend.feedbackConfigMigration.podSecurityContext) | nindent 8 }}
      serviceAccountName: {{ include "backend.serviceAccountName" . }}
      {{- with concat .Values.commonInitContainers .Values.backend.feedbackConfigMigration.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: config-migrations
          {{- with .Values.backend.feedbackConfigMigration.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with $envVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "langsmith.fullname" . }}-config
          image: {{ include "langsmith.image" (dict "Values" .Values "Chart" .Chart "component" "backendImage") | quote }}
          imagePullPolicy: {{ .Values.images.backendImage.pullPolicy }}
          resources:
            {{- toYaml .Values.backend.feedbackConfigMigration.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.backend.feedbackConfigMigration.securityContext | nindent 12 }}
          {{- with $volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.backend.feedbackConfigMigration.extraContainerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- with .Values.backend.feedbackConfigMigration.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.backend.feedbackConfigMigration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.feedbackConfigMigration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.feedbackConfigMigration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.feedbackConfigMigration.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
