{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langgraphDataplane.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "langgraphDataplane.labels" . | nindent 4 }}
  annotations:
    {{- include "langgraphDataplane.annotations" . | nindent 4 }}
data:
  deployment.yaml: |
{{ .Values.operator.templates.deployment | indent 4 }}
  service.yaml: |
{{ .Values.operator.templates.service | indent 4 }}
{{- end }}
