{{- if and .Values.agentBuilder.enabled .Values.agentBuilder.triggerServer.enabled .Values.agentBuilder.triggerServer.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.agentBuilder.triggerServer.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.agentBuilder.triggerServer.name }}
    {{- with .Values.agentBuilder.triggerServer.pdb.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.agentBuilder.triggerServer.pdb.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.agentBuilder.triggerServer.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.agentBuilder.triggerServer.name }}
{{- end }}

