{{- if and .Values.config.agentBuilder.enabled .Values.agentBuilderTriggerServer.enabled .Values.agentBuilderTriggerServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentBuilderTriggerServer.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.agentBuilderTriggerServer.name }}
    {{- with .Values.agentBuilderTriggerServer.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.agentBuilderTriggerServer.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.agentBuilderTriggerServer.serviceAccount.automountServiceAccountToken }}
{{- end }}

