{{- if .Values.insightsAgent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.fullname" . }}-clio-config
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    helm.sh/resource-policy: keep # This prevents helm from re-creating the config map on every upgrade
data:
{{- end }}