apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.playground.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.playground.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.playground.service.type }}
  {{- with .Values.playground.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerIP: {{ .Values.playground.service.loadBalancerIP }}
  ports:
    - name: playground
      port: {{ .Values.playground.service.port }}
      targetPort: playground
      protocol: TCP
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.playground.name }}
