apiVersion: v2
name: langgraph-dataplane
maintainers:
  - name: Ankush
    email: ankush@langchain.dev
description: Helm chart to deploy a langgraph dataplane on kubernetes.
type: application
version: 0.2.17
appVersion: "0.13.9"
