{{- if and .Values.agentBuilder.enabled .Values.agentBuilder.toolServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.agentBuilder.toolServer.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.agentBuilder.toolServer.name }}
    {{- with .Values.agentBuilder.toolServer.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.agentBuilder.toolServer.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.agentBuilder.toolServer.service.type }}
  {{- with .Values.agentBuilder.toolServer.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.agentBuilder.toolServer.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.agentBuilder.toolServer.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.agentBuilder.toolServer.service.port }}
      targetPort: {{ .Values.agentBuilder.toolServer.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.agentBuilder.toolServer.name }}
{{- end }}

