{{- if and .Values.agentBuilder.enabled .Values.agentBuilder.toolServer.enabled .Values.agentBuilder.toolServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agentBuilderToolServer.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.agentBuilder.toolServer.name }}
    {{- with .Values.agentBuilder.toolServer.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.agentBuilder.toolServer.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.agentBuilder.toolServer.serviceAccount.automountServiceAccountToken }}
{{- end }}

