{{- if not .Values.postgres.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.postgres.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.postgres.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.postgres.name }}
  {{- end }}
