{{- if not .Values.redis.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.redisSecretsName" .}}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.redis.external.enabled }}
  connection_url: {{ .Values.redis.external.connectionUrl | b64enc }}
  {{- else }}
  connection_url: {{ printf "redis://%s-%s:%v" (include "langsmith.fullname" .) .Values.redis.name .Values.redis.service.port | b64enc }}
  {{- end}}
{{- end }}
