{{- if not (or .Values.redis.disableSecretCreation .Values.redis.external.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.redisSecretsName" .}}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.redis.external.enabled }}
    {{- if .Values.redis.external.cluster.enabled }}
    {{ .Values.redis.external.cluster.nodeUrisSecretKey }}: {{ .Values.redis.external.cluster.nodeUris | toJson | b64enc | squote }}
    {{ .Values.redis.external.cluster.passwordSecretKey }}: {{ .Values.redis.external.cluster.password | default "" | b64enc | quote }}
    {{- else }}
    {{ .Values.redis.external.connectionUrlSecretKey }}: {{ .Values.redis.external.connectionUrl | b64enc }}
    {{- end }}
  {{- else }}
    connection_url: {{ printf "redis://%s-%s.%s.svc.%s:%v" (include "langsmith.fullname" .) .Values.redis.name (.Values.namespace | default .Release.Namespace) .Values.clusterDomain .Values.redis.service.port | b64enc }}
  {{- end}}
{{- end }}
