{{- if not .Values.redis.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.redis.name }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.redis.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.redis.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  {{- with .Values.redis.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerIP: {{ .Values.redis.service.loadBalancerIP }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
    {{- if .Values.redis.metrics.enabled }}
    - name: redis-metrics
      port: {{ .Values.redis.metrics.containerPort }}
      targetPort: {{ .Values.redis.metrics.containerPort }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.redis.name }}
{{- end }}
