{{- if .Values.authProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.authProxy.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with.Values.authProxy.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.authProxy.name }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with.Values.authProxy.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.authProxy.service.type }}
  {{- with .Values.authProxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  loadBalancerIP: {{ .Values.authProxy.service.loadBalancerIP }}
  ports:
    - name: envoy
      port: {{ .Values.authProxy.service.port }}
      targetPort: envoy
      protocol: TCP
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.fullname" . }}-{{ .Values.authProxy.name }}
{{- end }}
