{{- if .Values.queue.autoscaling.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.queue.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.queue.autoscaling.keda.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.queue.autoscaling.keda.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    {{- if .Values.queue.rollout.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "langsmith.fullname" . }}-{{ .Values.queue.name }}
  pollingInterval: {{ .Values.queue.autoscaling.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.queue.autoscaling.keda.cooldownPeriod }}
  initialCooldownPeriod: {{ .Values.queue.autoscaling.keda.initialCooldownPeriod }}
  minReplicaCount: {{ .Values.queue.autoscaling.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.queue.autoscaling.keda.maxReplicaCount }}
  fallback:
    {{- toYaml .Values.queue.autoscaling.keda.fallback | nindent 4 }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.queue.autoscaling.keda.scaleDownStabilizationWindowSeconds }}
          policies:
            - type: Percent
              value: {{ .Values.queue.autoscaling.keda.scaleDownPolicy.value }}
              periodSeconds: {{ .Values.queue.autoscaling.keda.scaleDownPolicy.periodSeconds }}
        scaleUp:
          policies:
            - type: Percent
              value: {{ .Values.queue.autoscaling.keda.scaleUpPolicy.value }}
              periodSeconds: {{ .Values.queue.autoscaling.keda.scaleUpPolicy.periodSeconds }}
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "{{ .Values.queue.autoscaling.keda.queueTargetSize }}"
        url: "http://{{ include "langsmith.fullname" . }}-{{ .Values.backend.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/metrics/queue/default"
        valueLocation: "queued"
        format: "json"
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.queue.autoscaling.keda.targetCPUUtilizationPercentage }}"
    - type: memory
      metricType: Utilization
      metadata:
        value: "{{ .Values.queue.autoscaling.keda.targetMemoryUtilizationPercentage }}"
{{- end }}
