apiVersion: v2
name: langgraph-cloud
maintainers:
  - name: Ankush
    email: ankush@langchain.dev
description: Helm chart to deploy the LangGraph Cloud application and all services it depends on.
type: application
version: 0.1.19
appVersion: "0.2.0"
