{{- if .Values.studio.enabled }}
{{- $volumes := concat .Values.commonVolumes .Values.studio.deployment.volumes -}}
{{- $volumeMounts := concat .Values.commonVolumeMounts .Values.studio.deployment.volumeMounts -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langGraphCloud.fullname" . }}-{{ .Values.studio.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langGraphCloud.labels" . | nindent 4 }}
    {{- with.Values.studio.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langGraphCloud.annotations" . | nindent 4 }}
    {{- with.Values.studio.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.studio.autoscaling.enabled }}
  replicas: {{ .Values.studio.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langGraphCloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langGraphCloud.fullname" . }}-{{ .Values.studio.name }}
  template:
    metadata:
      {{- with .Values.studio.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with.Values.studio.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langGraphCloud.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langGraphCloud.fullname" . }}-{{ .Values.studio.name }}
    spec:
      serviceAccountName: {{ include "studio.serviceAccountName" . }}
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.studio.deployment.priorityClassName }}
      priorityClassName: {{ .Values.studio.deployment.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.studio.deployment.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.studio.name }}
          env:
            - name: VITE_STUDIO_LOCAL_GRAPH_URL
              value: {{ .Values.studio.localGraphUrl | quote }}
            {{- with .Values.studio.deployment.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "langGraphCloud.image" (dict "Values" .Values "Chart" .Chart "component" "studioImage") | quote }}
          imagePullPolicy: {{ .Values.images.studioImage.pullPolicy }}
          ports:
            - name: studio
              containerPort: {{ .Values.studio.containerPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.studio.deployment.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.studio.deployment.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.studio.deployment.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.studio.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.studio.deployment.securityContext | nindent 12 }}
          {{- with $volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.studio.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.studio.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.studio.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
