{{- if and .Values.config.deployment.enabled .Values.hostBackend.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "langsmith.fullname" . }}-{{ .Values.hostBackend.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    {{- if .Values.hostBackend.rollout.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "langsmith.fullname" . }}-{{ .Values.hostBackend.name }}
  minReplicas: {{ .Values.hostBackend.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.hostBackend.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.hostBackend.autoscaling.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hostBackend.autoscaling.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.hostBackend.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hostBackend.autoscaling.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
